### PR TITLE
Doesn't work with non-bundled entities

### LINKED ISSUE #9: Doesn't work with non-bundled entities
Entities that don't have a bundle entity, such as user don't currently work.

### PR DESCRIPTION
**Pull request by benjy**
Patch indicates the problem, but it's probably the wrong fix. Fixes #9

### CODE REVIEW

**Comment by webflo** [comment]
I think the flag module had similar problems. We should look at their workaround/fix.

**Comment by benjy** [comment]
It seems that ER only shows the bundles to be selected when the entity has bundles. However, it forces you to select one therefore, presuming that no bundles means an entity type without a bundle maybe isn't all bad.

**Comment by slashrsm** [comment]
I'd personally prefer ER way (no bundles dropdown for non-bundled entities). It seems like a less hacky approach.

**Comment by benjy** [comment]
@slashrsm this patch adds it during in formElement, there is no bundles drop down for non-bundled entities from ER so this patch gives us that outcome.

**Comment by slashrsm** [comment]
Ah, right. I believe it is good to go.

**Comment by slashrsm** [comment]
Could we just add a comment above conditional to explain what is motivation behind this?

**Comment by benjy** [comment]
Done.

**Comment by webflo** [comment]
Sorry i don´t to be picky but i think no configured bundles means entity-type equals bundle is a wrong assumption. For example Node entities always have bundle because the ContentEntityType annotation defined a bundle key. In comparison User Entity has no bundle key.

**Comment by benjy** [comment]
ER forces you to select at least one bundle if the entity supports bundles. So, this can never be empty for entity types that have bundles.

> i think no configured bundles means entity-type equals bundle is a wrong assumption.

Well this is the assumption made in Entity\ContentEntityBase::__construct()

**Comment by slashrsm** [comment]
Hm... can we check if entity type is bundable and only apply this to it if not?

Would that work @webflo?

**Comment by benjy** [comment]
bump?

**Comment by slashrsm** [comment]
There are still some things to address here. We should move this to https://www.drupal.org/project/issues/search/inline_entity_form

**Comment by slashrsm** [comment]
https://www.drupal.org/node/2534320

**Comment by benjy** [comment]
Are all issues moving to Drupal.org now?

**Comment by slashrsm** [comment]
See my comment above. We moved all development to d.o a while ago.

**Pull request closed without merging**
