### PR TITLE
add a new table field type to render the cell value via a callback function

### PR DESCRIPTION
**Pull request by axe312ger**
Currently, the table fields of IEF can only contain entity properties. I'd like to add a new table field type to render the cell content via a callback function.

This is basically a port of [this patch](https://www.drupal.org/node/2375895#comment-9347583). We need this for our 8.x-1.x version of [Inline Entity Form Preview](https://www.drupal.org/project/inline_entity_form_preview).

### CODE REVIEW

**Comment by webflo** [comment]
@axe312ger @yannickoo The patch was committed to 8.x today in https://www.drupal.org/node/2324901. Thank you for your work!

**Comment by webflo** [comment]
https://www.drupal.org/node/2472769#comment-10108006

**Comment by yannickoo** [comment]
:heart_eyes:

**Comment by axe312ger** [comment]
thx!!!

**Pull request closed without merging**
